"""add new field to employee model

Revision ID: 34d2296242e4
Revises: 3b89617fecfa
Create Date: 2026-03-16 14:25:36.297781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d2296242e4'
down_revision: Union[str, Sequence[str], None] = '3b89617fecfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### add server_default='0' ###
    op.add_column(
        'employees',
        sa.Column('rate_per_hour', sa.Integer(), nullable=False, server_default='0')
    )

    # Иои явно обновляем существующие записи
    # op.execute("UPDATE employees SET rate_per_hour = 0 WHERE rate_per_hour IS NULL")
    
    # Теперь можно сделать NOT NULL
    # op.alter_column('employees', 'rate_per_hour', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'rate_per_hour')
    # ### end Alembic commands ###
